-- NOTE: use GHC flag -fcontext-stack42 with this module
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo.Polarization_types where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
polarization_types :: Table
    ((RecCons Id (Expr (Maybe Int))
      (RecCons Name (Expr String) RecNil)))

polarization_types = baseTable "polarization_types" $
                     hdbMakeEntry Id #
                     hdbMakeEntry Name

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data Id = Id

instance FieldTag Id where fieldName _ = "id"

xid :: Attr Id (Maybe Int)
xid = mkAttr Id

---------------------------------------------------------------------------
-- Name Field
---------------------------------------------------------------------------

data Name = Name

instance FieldTag Name where fieldName _ = "name"

name :: Attr Name String
name = mkAttr Name
