-- NOTE: use GHC flag -fcontext-stack44 with this module
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo.Projects where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
projects :: Table
    ((RecCons Id (Expr (Maybe Int))
      (RecCons Observer_id (Expr Int)
       (RecCons Telescope_id (Expr Int)
        (RecCons Name (Expr String) RecNil)))))

projects = baseTable "projects" $
           hdbMakeEntry Id #
           hdbMakeEntry Observer_id #
           hdbMakeEntry Telescope_id #
           hdbMakeEntry Name

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data Id = Id

instance FieldTag Id where fieldName _ = "id"

xid :: Attr Id (Maybe Int)
xid = mkAttr Id

---------------------------------------------------------------------------
-- Observer_id Field
---------------------------------------------------------------------------

data Observer_id = Observer_id

instance FieldTag Observer_id where fieldName _ = "observer_id"

observer_id :: Attr Observer_id Int
observer_id = mkAttr Observer_id

---------------------------------------------------------------------------
-- Telescope_id Field
---------------------------------------------------------------------------

data Telescope_id = Telescope_id

instance FieldTag Telescope_id where fieldName _ = "telescope_id"

telescope_id :: Attr Telescope_id Int
telescope_id = mkAttr Telescope_id

---------------------------------------------------------------------------
-- Name Field
---------------------------------------------------------------------------

data Name = Name

instance FieldTag Name where fieldName _ = "name"

name :: Attr Name String
name = mkAttr Name
