-- NOTE: use GHC flag -fcontext-stack45 with this module
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo.Receivers where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
receivers :: Table
    ((RecCons Id (Expr (Maybe Int))
      (RecCons Name (Expr String)
       (RecCons Min_freq (Expr Double)
        (RecCons Max_freq (Expr Double)
         (RecCons Band (Expr (Maybe String)) RecNil))))))

receivers = baseTable "receivers" $
            hdbMakeEntry Id #
            hdbMakeEntry Name #
            hdbMakeEntry Min_freq #
            hdbMakeEntry Max_freq #
            hdbMakeEntry Band

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data Id = Id

instance FieldTag Id where fieldName _ = "id"

xid :: Attr Id (Maybe Int)
xid = mkAttr Id

---------------------------------------------------------------------------
-- Name Field
---------------------------------------------------------------------------

data Name = Name

instance FieldTag Name where fieldName _ = "name"

name :: Attr Name String
name = mkAttr Name

---------------------------------------------------------------------------
-- Min_freq Field
---------------------------------------------------------------------------

data Min_freq = Min_freq

instance FieldTag Min_freq where fieldName _ = "min_freq"

min_freq :: Attr Min_freq Double
min_freq = mkAttr Min_freq

---------------------------------------------------------------------------
-- Max_freq Field
---------------------------------------------------------------------------

data Max_freq = Max_freq

instance FieldTag Max_freq where fieldName _ = "max_freq"

max_freq :: Attr Max_freq Double
max_freq = mkAttr Max_freq

---------------------------------------------------------------------------
-- Band Field
---------------------------------------------------------------------------

data Band = Band

instance FieldTag Band where fieldName _ = "band"

band :: Attr Band (Maybe String)
band = mkAttr Band
