-- NOTE: use GHC flag -fcontext-stack42 with this module
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo.Sources where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sources :: Table
    ((RecCons Id (Expr (Maybe Int))
      (RecCons Name (Expr String) RecNil)))

sources = baseTable "sources" $
          hdbMakeEntry Id #
          hdbMakeEntry Name

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data Id = Id

instance FieldTag Id where fieldName _ = "id"

xid :: Attr Id (Maybe Int)
xid = mkAttr Id

---------------------------------------------------------------------------
-- Name Field
---------------------------------------------------------------------------

data Name = Name

instance FieldTag Name where fieldName _ = "name"

name :: Attr Name String
name = mkAttr Name
